### ISSUE TITLE
Storybook typography 

### ISSUE THREAD

**Issue by syuan100** [ConsenSys/rimble-ui#105]
[Looks like the font isn't rendering correctly for the Storybook.](https://consensys.github.io/rimble-ui/?selectedKind=Typography%2FHeading&selectedStory=H1-H6&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Unless it's supposed to be Times New Roman, which I doubt? Was able to do some inspection and it looks like "inter-ui.css" is not loading, which in turn looks like isn't loading the font family "Inter UI" in the css.

<img width="1090" alt="screen shot 2018-11-01 at 11 33 59 am" src="https://user-images.githubusercontent.com/1700530/47871903-76bc8a00-ddca-11e8-9e8d-b987f723da65.png">

<img width="1560" alt="screen shot 2018-11-01 at 11 35 36 am" src="https://user-images.githubusercontent.com/1700530/47871916-7fad5b80-ddca-11e8-95ce-4d503d6553c5.png">

<img width="353" alt="screen shot 2018-11-01 at 11 35 56 am" src="https://user-images.githubusercontent.com/1700530/47871921-83d97900-ddca-11e8-9fb0-927a438ab42b.png">

**Comment by gesquinca** [comment]
Thanks @syuan100. We're working to fix this now.

**Comment by gesquinca** [comment]
Fonts rendering correctly now @syuan100 

https://consensys.github.io/rimble-ui/?selectedKind=Typography%2FHeading
