### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#129]
Loaders are used to communicate to a user that a potentially long-running task in process. 

When the expected wait time is relatively short, a loader alone may be sufficient. However, for very long-running tasks, consider other patterns and always provide additional information to properly set user expectations. 

Loaders should not be used to communicate an incomplete user action blocking the task (such as confirming a transaction in a wallet).

## Properties
- Size
- Color

**Comment by carolineford** [comment]
Looks good 👍
