### ISSUE TITLE
Allow theme overrides

### ISSUE THREAD

**Issue by barlock** [ConsenSys/rimble-ui#146]
It's not possible right now to extend the base theme provided by the rimble `ThemeProvider` without a lot of copy pasta. 

Proposed Api:
Export the default theme, and let `ThemeProvider` take an optional `theme` prop.

```js
import {theme, ThemeProvider} from 'rimble-ui';

const myTheme = {
  ...theme,
  overideProp: 'foo'
};

export default () => {
  <ThemeProvider theme={theme}></ThemeProvider>
}
```

**Comment by gesquinca** [comment]
Thanks for finding this @barlock! We're looking into it right now.

**Comment by gesquinca** [comment]
@barlock Does this fix the issue for you?

**Comment by gesquinca** [comment]
@barlock your proposed changes are live on v0.4.2! Thank you for contributing. 🎉

**Comment by barlock** [comment]
🙇 Thank you kindly sir!
