### ISSUE TITLE
Connection demo app: Blocking network modal

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#195]
Appears when a user initiates an on-chain action (like transaction) and is currently on the wrong network. Will auto-close when the network is correct. Should appear prior to a Connection Modal if on wrong network. Should resume the user-initiated action (like connect or transact).

- [ ] Modal
- [ ] Check network logic
- [ ] Tests

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/12
