### ISSUE TITLE
Connection demo app: Passive network indicator

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#196]
A user should see a network indicator displaying the connected network name and associated color.

Follow metamask’s network colors
Main - green
Ropsten - red
Kovan - purple
Rinkby - yellow

- [ ] Indicator component
- [ ] Network connection logic
- [ ] Tests

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/11
