### ISSUE TITLE
Connection demo app: Account summary block

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#205]
Show user connected status. Shows user short address. Shows current balance. If balance is low, style the balance in red. Currency internationalization? Maybe click on summary block, show dropdown with option to Disconnect. Can also be space for dApp specific-functionality/navigation. (no blockie here)

- [ ] Display public address (truncated)
- [ ] Display wallet balance 
- [ ] Low balance alternate presentation
- [ ] Currency conversion (check MM for this?)
- [ ] Dropdown on click
- [ ] Disconnect option
- [ ] Tests

![img1](/dl/zSAzCcXUqNMsHDnsirbWEw?slug=rimble-components)

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/22
