### ISSUE TITLE
Connection demo app: Low funds modal

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#206]
Preconditions: User is connected and verified

When a user initiates an on-chain action, or continued from a Connect Button action. Shows user public address. Show QR code action button. Continue button to close the modal. Can be cancelled/closed. Show the current network status.

- [ ] Check wallet balance
- [ ] PublicAddress with 'copy' button
- [ ] QR code icon button
- [ ] network indicator
- [ ] tests

![img1](/dl/BO5CaEt6hnKrMDnsird0xw?slug=rimble-components)

**Comment by MikeLockz** [comment]
https://github.com/ConsenSys/rimble-app-demo/issues/21
