### ISSUE TITLE
Connection demo app: Connection cancelled during verification

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#207]
Same as Connection cancelled modal but the primary action should return user to Verify Your Account Modal.

- [ ] Tests

![img1](/dl/qCkM7MSJt4PKSjnsirTMvw?slug=rimble-components)

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/20
