### ISSUE TITLE
Connection demo app: Verify Your Account modal

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#208]
Appears when there is an `eth.personal.sign` prompt in MetaMask. Should show public address user’s eth address. Should show network indicator. If user cancels from MetaMask prompt, go to Connection Cancelled During Verification Modal. Should recommend specific verbiage for the MetaMask prompt. When successful, show toast with truncated user address.

- [ ] PublicAddress
- [ ] Trigger success toast message
- [ ] Tests

![img1](/dl/gHvaUzkhf8GyTDnsirKPsQ?slug=rimble-components)

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/19
