### ISSUE TITLE
Connection demo app: Connection cancelled modal

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#209]
Appears if the user clicks “Cancel” from a MetaMask Connect prompt. Can be cancelled/closed. Secondary action is Browse as Guest which is the same as close. Send Request Again would re-trigger the MetaMask Connect prompt. The background modal should change to the Connection Pending Modal.

- [ ] Send request again button to trigger connect prompt
- [ ] Tests

![img1](/dl/Sj4ytjlLBypzBTnsiqyzQQ?slug=rimble-components)

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/18
