### ISSUE TITLE
Connection demo app: Connection pending modal

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#210]
Appears after user clicks the “Connect with MetaMask” button from the Connection Modal. Modal can be cancelled/closed. Prompts MetaMask with Connect prompt.

- [ ] Loader icon button
- [ ] Tests

![img1](/dl/VTLbMb3QcHBcnTnsiqvclQ?slug=rimble-components)

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/17
