### ISSUE TITLE
Connection demo app: Connection modal from on-chain action

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#211]
Variation for the connection modal displaying different content, which is triggered when a user initiates an on-chain action. Connect with MetaMask button is primary action. Modal can be cancelled/closed. Should include current network indicator. Might not make through testing.

- [ ] Connect with Metamask button
- [ ] Network indicator
- [ ] Test

![img1](/dl/Gd0kYXY_FC2z3DnsiqsG9g?slug=rimble-components)

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/16
