### ISSUE TITLE
Connection demo app: Connection modal - Metamask button

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#212]
Button appearing with Connection modal(s) that triggers a MetaMask connection request.

- [ ] Button style
- [ ] Trigger connection request
- [ ] tests

NOTE: This feature might be cut/changed based on in-progress user testing.

**Comment by MikeLockz** [comment]
Resolved by: https://github.com/ConsenSys/rimble-app-demo/issues/14
