### ISSUE TITLE
Connection demo app: Passive change network banner

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#214]
When a user is connected to the wrong network, she should see a bottom full-width banner which informs user to switch network.

Banner is persistent and cannot be dismissed
Banner is automatically dismissed when the user switches to the correct network

- [ ] Banner component
- [ ] Check network logic
- [ ] Tests

**Comment by MikeLockz** [comment]
https://github.com/ConsenSys/rimble-app-demo/issues/10
