### ISSUE TITLE
Connection demo app: Connection modal

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#215]
Triggered when user hits “Connect” button. Connect with MetaMask button is primary action. Modal can be cancelled/closed. Should include current network indicator.

- [ ] Connect with Metamask button
- [ ] Network indicator
- [ ] Test

![img1](/dl/F0UBSsoiQ7C93DnsiqpiaQ?slug=rimble-components)

**Comment by MikeLockz** [comment]
https://github.com/ConsenSys/rimble-app-demo/issues/15
