### ISSUE TITLE
Network Indicator

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#225]
**Is your feature request related to a problem? Please describe.**
I would like to know what network I am on and what network I am supposed to be on.

**Describe the solution you'd like**
I would like to see a colored circle that aligns with a network network name. The circle and name could represent either a desired network to which to connect or the current network that I am connected to. 

**Additional context**
Ideally this would be fed by a single point of input, possibly a network ID.

**Comment by zkalman** [comment]
Closing this issue in rimble-ui. Will re-open a related issue in appropriate repo.
