### ISSUE TITLE
Short Address

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#226]
As a user I want to see a shortened version of an Ethereum address. I should see the 0x, next 4 characters, 3 dots(...), and the last 4 characters of the address.

Optionally, I would like to be able to include props that would:
- enable 'click to copy' which puts the full address into the clipboard and visually indicates to the user that the address was successfully put into the clipboard
- enable 'click to expand' which would expand the address to show the full address
- enable visual modifications such as a background color and border radius or plain

**Comment by zkalman** [comment]
Closing this issue in rimble-ui. Will re-open a related issue in appropriate repo.
