### ISSUE TITLE
Ethereum Address Input

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#227]
As a user, I should have an input type that allows me to validate the input as a valid Ethereum address.

Should show red when the input is invalid.
Should show green when the input is valid.

Optionally should include the blockie for address when valid.

**Comment by ryancreatescopy** [comment]
Should display an error message if invalid.

**Comment by zkalman** [comment]
Closing this issue in rimble-ui. Will re-open a related issue in appropriate repo.
