### ISSUE TITLE
Wallet Summary

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#228]
As a user, I should see wallet address, blockie for the address, the account balance, and if the account balance is low.

Should show placeholder data when no address available for address and balance.
Should optionally enable the blockie
Should optionally handle a low balance.
Should optionally display tokens.
If low balance, calculate if balance is low and change balance color to red.

**Comment by zkalman** [comment]
Closing this issue in rimble-ui. Will re-open a related issue in appropriate repo.
