### ISSUE TITLE
Change Gas Modal

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#230]
As a user, I should see a blocking modal with 3 options for gas prices that represent and explain 3 speeds for transactions based on the gas. The gas price should also be represented in fiat currency. The modal should be closable. The modal should return the value of the gas price chosen by the user and close the modal.

**Comment by zkalman** [comment]
Closing this issue in rimble-ui. Will re-open a related issue in appropriate repo.
