### ISSUE TITLE
Transaction Summary

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#232]
A collapsible container that lists all relevant details of a transaction.

**Comment by ryancreatescopy** [comment]
Relevant details might include:
- Amount in ETH/FIAT
- Transaction fee in ETH/FIAT
+ (How is this worked out?) as an optional summary of gas limit etc.
- Recipient address
- Estimated speed?

**Comment by ryancreatescopy** [comment]
We also might want a pre/post transaction summary

Pre: to check the final details and double-confirm you want to go ahead
Post: so you can go back and review transactions with a relevant status (success/pending/failed) etc.

**Comment by zkalman** [comment]
Closing this issue in rimble-ui. Will re-open a related issue in appropriate repo.
