### ISSUE TITLE
Tooltip Causing Reflow

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#241]
**Describe the bug**
When using a tooltip, it will cause elements around it to reflow in unpredictable ways breaking layouts.

**To Reproduce**
1. Use a tooltip
2. Surround with different elements
3. When triggered, the tooltip causes reflow of surrounding elements

**Expected behavior**
Triggered tooltips should not affect the layout or flow of surrounding elements

**Screenshots**
![tooltip-reflow](https://user-images.githubusercontent.com/797290/55650718-bafded00-57a3-11e9-9898-94e486d34194.gif)

![image](https://user-images.githubusercontent.com/797290/55650662-9e61b500-57a3-11e9-98ca-3e1ebfd562e6.png)

**Comment by gesquinca** [comment]
@MikeLockz can we get a live example of this?

**Comment by MikeLockz** [comment]
Could not recreate for debugging.
