### ISSUE TITLE
Simple Ethereum public address 

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-ui#250]
As a user I want to see a simpler version of an Ethereum address in parts of a UI that don't have a lot of space.

Something like this:
<img width="696" alt="Screenshot 2019-04-17 12 46 18" src="https://user-images.githubusercontent.com/6794540/56305782-e3280d00-610e-11e9-817c-430bb03368ce.png">

# Acceptance criteria

- Component accepts the following inputs:
    - Full address
- Component outputs a styled address in one of two formats
    - Full address
    - Truncated

- [ ] Documentation
- [ ] Tests

**Comment by sublimatedpotato** [comment]
I would love to put in a PR for this if it's not being worked on, yet. Was the thought to have this be an update to the existing PublicAddress component or a separate component in itself?

**Comment by zkalman** [comment]
@sublimatedpotato Thanks for your interest! This one is toward the top of our backlog. We are doing sprint planning tomorrow and will decide how to handle it then. We will check back in with you right after that. Thanks again!

**Comment by sublimatedpotato** [comment]
Sounds great. Thanks @zkalman

**Comment by gesquinca** [comment]
@sublimatedpotato we'll be building something similar to this implementation if you want to take a look here. 

https://github.com/ConsenSys/rimble-ui/blob/a69e1c838572f9c29418571e5f039b7c1b74b031/src/PublicAddress/ShortAddress.js

It's a separate component until we can re-architect some larger aspects of the library. I imagine a good amount of back-and-forth with any code contributions. Feel free to cut a branch, submit a PR, and we can go from there.

**Comment by sublimatedpotato** [comment]
Thanks @gesquinca I'll work to get something submitted in the next couple days. 

Do you have any initial thoughts on exposing the `addressSummary` arguments (i.e. `firstSegLength`, `lastSegLength`, `includeHex`) as properties on the component?

**Comment by gesquinca** [comment]
Awesome, thanks. 

@sublimatedpotato I'm not sure. I think we should because that seems like the most flexible thing to do, but on the other hand, I think that would introduce more opportunities for further inconsistency in the space. That being said, I think we should probably not expose them for now. What are your thoughts? 

I also think we would abstract `addressSummary ` to some type of `utils/` directory in the future.

**Comment by sublimatedpotato** [comment]
@gesquinca I agree that exposing the `addressSummary` args via props will make the component more flexible for the end-user, but will definitely defer to your line of thinking on _when_ that should happen. You're much more involved with the project at this point and so will have a better grasp of proper timing and its reflection on the project as a whole.

I also agree that `addressSummary` in general is a prime target for a utility in the future

As far as the component itself I'm not seeing too much to adjust in what you've built out previously. Here's what I'm thinking:
* add `truncate` boolean prop that toggles whether the full address or the `addressSummary` is displayed
* possible switch to `document.execCommand('copy')` as used in `PublicAddress`. This would eliminate the need for an additional dependency just for this component, but I believe would require displaying the text under a `<span>` tag somehow OR possible a hidden input. Do you have any thoughts on this?
* add tests for the component:

- [ ] snapshot
- [ ] renders
- [ ] displays full address when `truncate` prop is false
- [ ] displays full `addressSummary` when `truncate` prop is true
- [ ] calls to set text to clipboard when clicked
* add Story docs for component, demonstrating both full and truncated display

Let me know your thoughts on the preferred clipboard copy approach and anything else regarding the above and I'll get to work writing some code. Thanks!

**Comment by gesquinca** [comment]
@sublimatedpotato This component only needs to satisfy this requirement:

- add truncate boolean prop that toggles whether the full address or the addressSummary is displayed

copy/paste functionality, etc, would be part of a larger component. The implementation we have right now is only a reference because we need to abstract the truncating of the address away from what we have here. Does that make sense?

**Comment by sublimatedpotato** [comment]
@gesquinca ok, yes. I'll work it up and get a PR submitted.

**Comment by MikeLockz** [comment]
Release in 0.9.0
