### ISSUE TITLE
'Form' is not export from 'rimble-ui'

### ISSUE THREAD

**Issue by crazyrabbitLTC** [ConsenSys/rimble-ui#256]
**Describe the bug**
For whatever reason, I'm getting this error when trying to use the `Form` elements. I can use `Button`, just fine for example.

Error I am getting:
`Attempted import error: 'Form' is not exported from 'rimble-ui'.`

I 

**To Reproduce**
In my case:
`npm install --save rimble-ui styled-components`

follow example here: 

https://consensys.github.io/rimble-ui/?path=/story/components-form-form--documentation

**Expected behavior**

Expected it to import, rather surprised it doesn't. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Firefox brower. 66.0.3 (64-bit)
OSX 10.14.4

**Additional context**

**Comment by gesquinca** [comment]
@crazyrabbitLTC can you send me which version of rimble-ui you're using in your package.json?

**Comment by gesquinca** [comment]
Should be resolve with this PR:

https://github.com/zeppelinos/zepkit/pull/12
