### ISSUE TITLE
ToolTips don't work as Expected : Incorrect Text and Don't "pop Over"

### ISSUE THREAD

**Issue by crazyrabbitLTC** [ConsenSys/rimble-ui#257]
**Describe the bug**
Tool Tips do not pop over all the content as expected. 

This code: 
```

      <Tooltip message="Mint it daddio!" placement="top">
        <OutlineButton>Mint</OutlineButton>
      </Tooltip>
```
Renders: "Popper content" rather than "Mint it daddio!".

The text of the ToolTip is always: "Popper content" regardless of what is passed as `message`

**To Reproduce**
Use the ToolTip on a button as described in the documentation.

**Expected behavior**
Expect to have the message be the message passed in the component.

**Screenshots**

**Desktop (please complete the following information):**
Browser: FireFox 
OSX: 10.14.4

**Additional context**
![Screen Shot 2019-04-26 at 7 53 25 PM](https://user-images.githubusercontent.com/1938013/56841658-19773200-685d-11e9-9764-369df7d2b6c0.png)

**Comment by zkalman** [comment]
Hi Dennison. Thanks for raising this issue. We will be looking into it.

**Comment by gesquinca** [comment]
@crazyrabbitLTC  can you send me which version of rimble-ui you're using in your package.json?

**Comment by gesquinca** [comment]
@crazyrabbitLTC can you try updating your version of rimble and seeing if that resolves your issue? 

`yarn add rimble-ui@latest`

**Comment by gesquinca** [comment]
@crazyrabbitLTC I have a strong suspicion this is because Zepkit uses an older version of `rimble-ui`. I opened a PR on their codebase to update their version. 
https://github.com/zeppelinos/zepkit/pull/12

In the meantime, updating the version in your `/client` folder with `npm install --save rimble-ui@latest` should fix this.
