### ISSUE TITLE
Flash component does not wrap text

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#262]
**Describe the bug**
When there is an amount of text that exceeds the width of a wrapping Flash component, the text does not stay inside of the Flash component.

**To Reproduce**
```
<Flash>
  <Text>I am a really really long string of text.</Text>
</Flash
```

**Expected behavior**
The text should always stay inside of its parent element.

**Screenshots**
![image](https://user-images.githubusercontent.com/797290/56926118-2890f680-6a8e-11e9-9c64-aec35371d2db.png)

**Rimble UI Version**

- 0.7.1 (latest)

**Comment by MikeLockz** [comment]
Live example: https://thirsty-archimedes-a2edb8.netlify.com/api-reference/ConnectionBanner

**Comment by gesquinca** [comment]
This is because the component is wrapped in a `<pre>` tag which sets `white-space: pre`. Not sure if this is a bug or not.
