### ISSUE TITLE
Tooltip content doesn't wrap

### ISSUE THREAD

**Issue by ryancreatescopy** [ConsenSys/rimble-ui#275]
**Describe the bug**
Tooltip doesn't wrap and goes off the screen on small screen sizes

**Expected behavior**
Tooltip should wrap so that all tooltip text is visible and not off-screen

**Screenshots**
![image](https://user-images.githubusercontent.com/40891631/57858512-1b436e00-77e9-11e9-99f2-6ed9459fd496.png)

**Rimble UI Version**
- latest

**Desktop (please complete the following information):**
 - Mac OS
 - Brave
 - 0.63.48

**Additional context**
This was using a desktop browser, but I changed the window size to see what it would display like on a mobile device.

**Comment by MikeLockz** [comment]
Needs additional research to find possible solutions. @MikeLockz will add a failing example.

**Comment by MikeLockz** [comment]
Example: https://codesandbox.io/embed/heading-margin-bug-bhe6u

I think we can close this issue if we move the tooltip placement to the bottom.

**Comment by MikeLockz** [comment]
Couldn't recreate in sandbox. Resolved by new layout in app.
