### ISSUE TITLE
Add propTypes for all components

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#291]
**Is your feature request related to a problem? Please describe.**
We can't release the new documentation site until we can get the props autogenerated from the rimble-ui source.

**Describe the solution you'd like**
Add component descriptions, propTypes and prop descriptions like:

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

/**
 * General component description.
 */
class MyComponent extends Component {
  render() {
    // ...
  }
}

MyComponent.propTypes = {
  /**
   * Description of prop "foo".
   */
  foo: PropTypes.number.isRequired,
  /**
   * Description of prop "bar" (a custom validation function).
   */
  bar: function(props, propName, componentName) {
    // ...
  },
  baz: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
};

MyComponent.defaultProps = {
  bar: 21,
};

export default MyComponent;
```

**Describe alternatives you've considered**
We could keep the current props tables but they would be harder to maintain.

**Comment by gesquinca** [comment]
closed by #325
