### ISSUE TITLE
Slider doesn't have line in FireFox

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#296]
**Describe the bug**
The Slider component does not have a visible "track" line on which the circle moves in FireFox.

![image](https://user-images.githubusercontent.com/797290/58898956-0277fb00-86b9-11e9-818e-dfa527bccf15.png)

**To Reproduce**

Open in Firefox:
https://codesandbox.io/embed/slider-component-bug-q5gh4

**Expected behavior**
Should have a colored line underneath the circle.

**Rimble UI Version**

- 0.9.0 (latest)

**Comment by sublimatedpotato** [comment]
This appears to be a result of the pseudo-elements. If you look at the Sandbox link in Firefox the `thumb` isn't being correctly styled either.

Currently used pseudo-element for the range is `[-webkit-slider-runnable-track](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-slider-runnable-track)`. Browser specific complements are:
* Mozilla: `[-moz-range-track](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-track)`
* Edge: `[-ms-track](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-track)`

Currently used pseudo-element for thumb is `[-webkit-slider-thumb](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-slider-thumb)`. Browser specific complements are:
* Mozilla: `[-moz-range-thumb](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-thumb)`
* Edge: `[-ms-thumb](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-thumb)`

I can submit a PR today with these fixes if you like.

**Comment by MikeLockz** [comment]
@sublimatedpotato thanks for the quick response on this bug! It has already been fixed in PR #298. Appreciate your time and attention.
