### ISSUE TITLE
Please provide example of PublicAddress wired up so 'copy' is functional

### ISSUE THREAD

**Issue by sampsojp** [ConsenSys/rimble-ui#320]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MikeLockz** [comment]
Not sure what happened but it looks like we lost some functionality on the PublicAddress component. Looking into it now, thanks for flagging.

**Comment by gesquinca** [comment]
@sampsojp Looks like there's a bug in the previous version of our build. Should be working in version 0.9.3.

**Comment by sampsojp** [comment]
Thank you.
