### ISSUE TITLE
Text can't be made bold without <b>

### ISSUE THREAD

**Issue by ryancreatescopy** [ConsenSys/rimble-ui#336]
**Describe the bug**
`<Text bold>bold text</Text>` doesn't produce bold text.

**To Reproduce**
You can see it in our docs: https://rimble.consensys.design/components/rimble-ui/Text

**Expected behavior**
The text should be bold with the `bold` prop

**Screenshots**

**Rimble UI Version**

**Comment by gesquinca** [comment]
@ryancreatescopy We're using the fontWeight prop to set that now. Something like this should work. 

```
<Text fontWeight={'bold'}>bold text</Text>
```

**Comment by gesquinca** [comment]
Need to update documentation
