### ISSUE TITLE
`onChange` event does not fire when using file `<Input type="file" />` component

### ISSUE THREAD

**Issue by pythonpete32** [ConsenSys/rimble-ui#359]
**Describe the bug**
when using the component onChange does not fire an event

**To Reproduce**
`<Input type="file" onChange={(e) => console.log(e)} /> {/* Broken */}`

Returns `undefined`
**Expected behavior**
event to be logged to console

**Screenshots**

**Rimble UI Version**

0.9.7

**Comment by gesquinca** [comment]
Hello @pythonpete32, thank you for finding this. It should be fixed in the latest version of the package. Let us know if it is working properly now.

**Comment by pythonpete32** [comment]
thanks it's working
