### ISSUE TITLE
Single-Side Borders Not Working

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#362]
**Describe the bug**
Single side border properties do not display a border according to the rimble docs which state that all border properties from styled-system are supported. 

![image](https://user-images.githubusercontent.com/797290/65051132-cabe5780-d925-11e9-8bea-b18a1621ca03.png)

The spec from styled-system supports styling a single side to any component.

![image](https://user-images.githubusercontent.com/797290/65050984-8468f880-d925-11e9-803a-142520861739.png)

https://github.com/styled-system/styled-system/blob/master/docs/table.md#border

**To Reproduce**
1. Create Box component
2. Add borderRight... props
3. No borders visible

**Expected behavior**
Should show right side border only.

**Screenshots**
https://codesandbox.io/embed/border-right-bug-038i1

**Rimble UI Version**

- 0.9.6 (latest)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gesquinca** [comment]
My guess is that these properties are part of styled system 5. This library uses styled-system 4. Can you verify @MikeLockz ?

See #301

**Comment by MikeLockz** [comment]
@gesquinca Ya those props are for 5x. Opened a new ticket on the storefront to update the link in the docs to point to the props tables for 4.x version.

Will be resolved by https://github.com/ConsenSys/rimble-storefront/issues/56
