### ISSUE TITLE
Links inside Flash are not colored

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-ui#378]
**Describe the bug**
A Link component inside of a Flash component should be styled to match the variant of Flash.

**To Reproduce**
1. Nest a Link inside of a Flash
2. Link is colored blurple, not variant color

https://codesandbox.io/embed/flash-link-color-bug-bs3us

**Expected behavior**
Links should be same color as Flash variant.

**Screenshots**
![image](https://user-images.githubusercontent.com/797290/66815619-8ef1ce80-ef73-11e9-82f2-07404367fd67.png)

**Rimble UI Version**

- 0.10.0 (latest)

**Comment by gesquinca** [comment]
@MikeLockz I don't think this is a valid bug. Can you verify?

**Comment by MikeLockz** [comment]
Correct, not a bug. Docs were wrong and have already been updated.
