### ISSUE TITLE
Docs: Empty page for Textarea component documentation

### ISSUE THREAD

**Issue by jakubkoci** [ConsenSys/rimble-ui#382]
**Describe the bug**
There is an empty page when I click on the Textarea component in the documentation.

**To Reproduce**
1. Go to https://rimble.consensys.design/components/rimble-ui/Textarea
2. See empty screen with no content

**Expected behavior**
There should be a documentation for Textarea component as it works for every other component.

**Screenshots**
![image](https://user-images.githubusercontent.com/676169/67165642-fcdd3200-f387-11e9-893b-6548cabb55da.png)

**Rimble UI Version**

- 0.7.1 (latest)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by MikeLockz** [comment]
Fixed in https://github.com/ConsenSys/rimble-storefront/pull/95

**Comment by MikeLockz** [comment]
https://deploy-preview-95--rimble-storefront.netlify.com/components/rimble-ui/Textarea
