### ISSUE TITLE
Uncaught Error: input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`

### ISSUE THREAD

**Issue by jayinprod** [ConsenSys/rimble-ui#447]
### rimble-ui Select

I am trying to use rimble-ui Select input but getting error  

    Uncaught Error: input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

source : https://rimble.consensys.design/components/rimble-ui/Select

codesandbox : https://codesandbox.io/s/recursing-bartik-rrp1v?fontsize=14&hidenavigation=1&theme=dark

Thanks

**Comment by MikeLockz** [comment]
Hi @jay15994 - I think if you change your `styled-components` dependency to something on version 4.xx you should not get the error anymore. 

We will update our docs to reflect the dependency on SC4 until we can get the library on the latest v5 version.

**Comment by jayinprod** [comment]
@MikeLockz 
thanks for help
downgrading to `styled-components@4.4.1` solved my problem
